options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Disallows
  no-color-literals: 0
  no-ids: 0
  no-important: 0
  no-qualifying-elements: 0
  no-vendor-prefixes: 0

  # Nesting
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Style Guide
  clean-import-paths: 0
  hex-length: 0
  leading-zero: 0
  nesting-depth: 0
  property-sort-order: 0
  quotes: 0
  shorthand-values: 0
  url-quotes: 0
  no-transition-all: 0

  linters:
    SelectorFormat:
      convention: hyphenated_BEM
