#!/usr/local/bin/node

const express = require(process.env.NODE_PATH + 'express');
const morgan = require('morgan')
const app = express();
const PORT = process.argv[2];
app.use(morgan('combined'));
app.use((req, res, next) => {
  if(req.headers['x-forwarded-proto'] == "http"){
    res.redirect("https://" + req.headers['host'] + req.url);
  } else {
    return next();
  }
});

app.use(express.static(__dirname + '/'));


app.listen(PORT, () => {
  console.log(`Server started at port ${PORT}.`);
});