default: &default
  docker:
    - image: circleci/node:8.4.0
  working_directory: ~/art-dashboard  
restore_cache: &restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
install_dependencies: &install_dependencies  
  run:
    name: install dependencies
    command: sudo npm install
save_cache: &save_cache 
  save_cache:
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - ./node_modules   

version: 2
jobs:
  build:
    <<: *default
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache
  tests:
    <<: *default
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run:
          name: run tests
          command: npm run coverage
      - run:
          name: submit coverage results
          command: npm run coveralls
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - tests:
          requires:
            - build