import KeyMirror from '../_utils/KeyMirror';

const CONSTANTS = KeyMirror({
  LOAD_ASSETS_SUCCESS: true,
  LOAD_ASSETS_FAILURE: true,
  LOAD_ASSETS_STARTS: true,
  LOAD_ASSET_TYPE_SUCCESS: true,
  LOAD_ASSET_TYPE_FAILURE: true,
  LOAD_CATEGORIES_SUCCESS: true,
  LOAD_CATEGORY_FAILURE: true,
  LOAD_SUBCATEGORIES_SUCCESS: true,
  LOAD_ASSET_TYPES_SUCCESS: true,
  LOAD_ASSET_MAKES_SUCCESS: true,
  LOAD_ASSET_MODEL_NUMBERS: true,
  CREATE_ASSET_SUCCESS: true,
  CREATE_ASSET_FAIL: true,
  LOAD_FEEDBACK_SUCCESS: true,
  LOAD_FEEDBACK_FAILURE: true,
  CREATE_MODEL_NUMBER_SUCCESS: true,
  CREATE_MODEL_NUMBER_FAILURE: true,
  UPDATE_TOAST_MESSAGE_CONTENT: true,
  RESET_TOAST_MESSAGE_CONTENT: true,
  CREATE_CATEGORY_FAILURE: true,
  CREATE_CATEGORY_SUCCESS: true,
  LOAD_ALLOCATIONS_SUCCESS: true,
  LOAD_ALLOCATIONS_FAILURE: true,
  LOADING_ALLOCATIONS: true
});

export default CONSTANTS;
