import KeyMirror from '../_utils/KeyMirror';

const CONSTANTS = KeyMirror({
  LOAD_ASSETS_SUCCESS: true,
  LOAD_ASSETS_FAILURE: true,
  LOAD_ASSET_TYPE_SUCCESS: true,
  LOAD_ASSET_TYPE_FAILURE: true,
  LOAD_CATEGORIES_SUCCESS: true,
  LOAD_SUBCATEGORIES_SUCCESS: true,
  LOAD_ASSET_TYPES_SUCCESS: true,
  LOAD_ASSET_MAKES_SUCCESS: true,
  LOAD_ASSET_MODEL_NUMBERS: true,
  CREATE_ASSET_SUCCESS: true,
  CREATE_ASSET_FAIL: true,
  LOAD_FEEDBACK_SUCCESS: true,
  LOAD_FEEDBACK_FAILURE: true,
  CREATE_MODEL_NUMBER_SUCCESS: true,
  CREATE_MODEL_NUMBER_FAILURE: true,

});

export default CONSTANTS;
