import KeyMirror from '../_utils/KeyMirror';

const CONSTANTS = KeyMirror({
  LOGIN_USER_SUCCESS: true,
  LOGIN_USER_FAILURE: true,
  LOAD_ASSET_TYPE_SUCCESS: true,
  LOAD_ASSET_TYPE_FAILURE: true,
  LOAD_CATEGORIES_SUCCESS: true,
  LOAD_SUBCATEGORIES_SUCCESS: true,
  LOAD_ASSET_TYPES_SUCCESS: true,
  LOAD_ASSET_MAKES_SUCCESS: true,
  LOAD_ASSET_MODEL_NUMBERS: true,
  CREATE_ASSET_SUCCESS: true,
  CREATE_ASSET_FAIL: true
});

export default CONSTANTS;
